//! Integrity checks for the committed media fixtures.
//!
//! The clips under `tests/fixtures/media/` are generated by
//! `tools/gen_media.sh` (FFmpeg, CC0). They back download/player tooling
//! and this test pins their basic well-formedness: they must exist, be
//! non-trivial, and carry a real MP4 `ftyp` box.

use std::fs;
use std::path::Path;

const FIXTURES: &[(&str, u64)] = &[
    ("testsrc.mp4", 10_000),
    ("bars.mp4", 2_000),
    ("black.mp4", 1_000),
];

fn fixture_dir() -> std::path::PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("fixtures")
        .join("media")
}

#[test]
fn fixtures_exist_and_are_nontrivial() {
    for (name, min_bytes) in FIXTURES {
        let path = fixture_dir().join(name);
        assert!(
            path.exists(),
            "fixture {} is missing — run tools/gen_media.sh",
            path.display()
        );
        let len = fs::metadata(&path).unwrap().len();
        assert!(
            len >= *min_bytes,
            "fixture {name} looks truncated ({len} bytes < {min_bytes})"
        );
    }
}

#[test]
fn fixtures_are_real_mp4_containers() {
    for (name, _) in FIXTURES {
        let path = fixture_dir().join(name);
        let bytes = fs::read(&path).unwrap();
        assert!(bytes.len() >= 12, "{name}: too short for an MP4 header");
        assert_eq!(&bytes[4..8], b"ftyp", "{name}: missing ftyp box");
        // The brand string right after the box size+type is printable ASCII.
        let brand: Vec<char> = bytes[8..12].iter().map(|b| *b as char).collect();
        let brand: String = brand.into_iter().filter(|c| c.is_ascii()).collect();
        assert!(!brand.is_empty(), "{name}: empty major brand");
    }
}

#[test]
fn fixtures_differ_from_each_other() {
    // A regeneration bug that writes the same clip everywhere is exactly
    // the kind of thing this suite exists to catch.
    let hashes: Vec<(String, u64)> = FIXTURES
        .iter()
        .map(|(name, _)| {
            let bytes = fs::read(fixture_dir().join(name)).unwrap();
            let hash = bytes
                .iter()
                .fold(0u64, |acc, b| acc.wrapping_mul(31).wrapping_add(*b as u64));
            (name.to_string(), hash)
        })
        .collect();
    for i in 0..hashes.len() {
        for j in (i + 1)..hashes.len() {
            assert_ne!(
                hashes[i].1, hashes[j].1,
                "{} and {} are identical — regenerate with tools/gen_media.sh",
                hashes[i].0, hashes[j].0
            );
        }
    }
}
